language: bash
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"


# install dependencies
install:
  - pip install -r requirements.txt
  #- pip install .
  
before_script:
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

# command to run tests
script:
  - ls
  #- travis_wait 40 coverage run -m pytest tests/
  - bash tests/test_build.sh
